# Generated by Django 3.2.5 on 2021-07-25 15:41

from django.db import migrations, models
import objetos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0002_auto_20210724_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='imagenes',
            field=models.TextField(default='', validators=[objetos.validators.validate_base64]),
        ),
    ]
