# Generated by Django 3.2.5 on 2021-07-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0003_objeto_imagenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transaccion', models.DateTimeField(auto_now=True)),
                ('json', models.TextField()),
                ('status', models.IntegerField()),
                ('errores', models.TextField()),
            ],
        ),
    ]
