# Generated by Django 3.2.5 on 2021-07-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0004_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='accion',
            field=models.CharField(choices=[('AD', 'Add'), ('UD', 'Update')], default='AD', max_length=2),
        ),
    ]
