# Generated by Django 3.2.5 on 2021-07-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0005_transaccion_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='estatus',
            field=models.CharField(choices=[('AC', 'Active'), ('AR', 'Archived'), ('DR', 'Draft')], max_length=2),
        ),
    ]
