# Generated by Django 3.2.5 on 2021-07-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0007_transaccion_corregida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='estatus',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('draft', 'Draft')], max_length=8),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='accion',
            field=models.CharField(choices=[('add', 'Add'), ('update', 'Update')], default='add', max_length=7),
        ),
    ]
