# Generated by Django 3.2.5 on 2021-07-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetos', '0008_auto_20210726_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
